### ISSUE TITLE
條目「大不列顫及北愛爾蘭聯合王國」沒有正確被parsed出英語

### ISSUE THREAD

**Issue by ethantw** [g0v/moedict-process#16]
Unlike [美利堅合眾國](https://www.moedict.tw/美利堅合眾國)，[大不列顛與北愛爾蘭聯合王國](https://www.moedict.tw/大不列顛與北愛爾蘭聯合王國)沒有被解析出英文。

![screen shot 2016-07-07 at 19 18 53](https://cloud.githubusercontent.com/assets/31068/16651638/ed1607ba-4477-11e6-97d9-a20ec7698631.png)
![screen shot 2016-07-07 at 19 17 27](https://cloud.githubusercontent.com/assets/31068/16651641/ee45eb8c-4477-11e6-9e92-142614d7f8ed.png)

**Comment by kcwu** [comment]
原始資料的格式就不一樣
http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000028969
http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000040539

**Comment by audreyt** [comment]
已經回報給上游，等待回應中。

**Comment by audreyt** [comment]
上游已經改正。目前教育部國語辭典公眾授權網還在 2015_20160523，下次更新時會自動修正。

```
「大不列顛與北愛爾蘭聯合王國」之英文名稱係因受限早期資料庫欄位長度而置於釋義欄，
本院目前已調整至詞目欄，以統一全典體例形式。感謝您來信提醒。
```

**Comment by kcwu** [comment]
其他有類似問題的詞條
https://www.moedict.tw/區域網路
https://www.moedict.tw/大利比亞阿拉伯人民社會主義群眾國
https://www.moedict.tw/奈及利亞聯邦共和國
search def =~ /^[(（][A-Z]/ 會發現更多

好奇體例怎麼決定什麼情況下要把外文名寫到詞目欄, "編輯說明" 中我一時沒找到.
我發現有的人名、地名會寫到詞目欄, 有的不會.

**Comment by audreyt** [comment]
感覺上是化學元素（有簡稱著）和有岐義者不標。

已經向上游回報：

```
區域網路
大利比亞阿拉伯人民社會主義群眾國
奈及利亞聯邦共和國（FederalRepublic ofNigeria，應為 Federal Republic of Nigeria）
關稅及貿易總協定
```
