### ISSUE TITLE
Entry 爻 was not correctly parsed

### ISSUE THREAD

**Issue by rschiang** [g0v/moedict-process#17]
The current entry of [爻](https://www.moedict.tw/%E7%88%BB) contains graphical character from I Ching. It now reads:

> 八卦上的橫線，長的全線「{[8ebd._104_0.gif;」稱為「陽爻」，斷開的兩段線「&8ebc]}」稱為「陰爻」。每三爻合成一卦，共八卦，而二卦相重可得六十四卦。

Which should be ⚊ (U+268A, symbol of yang) and ⚋ (U+268B, symbol of ying):

> 八卦上的橫線，長的全線「⚊」稱為「陽爻」，斷開的兩段線「⚋」稱為「陰爻」。每三爻合成一卦，共八卦，而二卦相重可得六十四卦。

**Comment by rschiang** [comment]
@audreyt @kcwu ……應該是回報在這裡吧？XD

**Comment by audreyt** [comment]
是這邊沒錯~

**Comment by kcwu** [comment]
看起來是 https://github.com/g0v/moedict-data/commit/446330e06c82e2100c569db0dada0d348f12f956 那個版本的 excel 檔裡面, 一些圖檔的檔名規則改變, 導致 parse 出怪怪的東西.

**Comment by kcwu** [comment]
又好像是因為 https://github.com/g0v/moedict-process/blob/master/parse.py#L184 那 regex `.*` 太 greedy 造成的

**Comment by lanfon72** [comment]
[魚水](https://www.moedict.tw/#魚水)跟[公因式](https://www.moedict.tw/#公因式)也有類似的問題，
` {[` 開頭的(eg. `{[fe41._104.0.gif;`)如果會自動轉的話補個 `?` => `&(.*?)\._104_0\.gif;` 應該就可以了?
