### ISSUE TITLE
「相位」的解釋和翻譯不同

### ISSUE THREAD

**Issue by miaoski** [g0v/moedict-process#30]
「相位」在國語辭典裡解釋成「宰相的位子」而不是電學裡面的相位，但是英譯、法譯、德譯都是電學裡面的相位。

**Comment by audreyt** [comment]
上游的內容請用這個連結裡的「意見反應」：
http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000110252
